### ISSUE TITLE
Link highlighting in bottom 'more-info' container broken on mobile

### ISSUE THREAD

**Issue by mehan** [mozilla/nsf-challenge#95] opened 2017-06-15 19:58 UTC
Screenshot was taken in iOS Chrome. The link works, though the yellow underline is not visible. 

![unnamed 3](https://user-images.githubusercontent.com/1390212/27199257-3331c616-51ca-11e7-8c38-30d18fc26952.jpg)

**Comment by ScottDowne** [comment] 2017-06-15 20:43
Hm, I'm seeing it working on both android ff and iphone 6 and 6S plus with chrome.

**Comment by mehan** [comment] 2017-06-15 22:26
Interesting. I'm also on an iPhone 6--works in iOS Firefox but not Chrome.

**Comment by hannahkane** [comment] 2017-07-03 17:29
I also can't reproduce on an iPhone 6 or 7 with Chrome.

**Comment by mehan** [comment] 2017-07-07 22:20
Well, feel free to close this one if I'm the only person who's seeing it. 🙂

**Comment by hannahkane** [comment] 2017-07-07 23:38
But you're the most important user!

Is the underline visible in other links on the page - like the "34 million people" link in the first paragraph?

**Comment by mehan** [comment] 2017-07-10 20:47
@hannahkane As it turns out, the link in question and all other links on the page now display correctly for me. It must just have been whatever outdated version of iOS Chrome I was using at the time. Thanks!

**Comment by hannahkane** [comment] 2017-07-10 20:51
ok, cool. closing then!

**Closed as completed by hannahkane** 2017-07-10 20:51 UTC
